name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for syntax errors
      run: node -c src/index.js
    
    - name: Verify project structure
      run: |
        test -f src/index.js
        test -d src/commands/prefix
        test -d src/commands/slash
        test -d src/events
        test -d src/utils
        test -f .env.example
        test -f package.json
        test -f README.md
    
    - name: Check environment example
      run: |
        grep -q "DISCORD_TOKEN" .env.example
        grep -q "CLIENT_ID" .env.example
        grep -q "PREFIX" .env.example
        grep -q "DEBUG" .env.example

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check package.json format
      run: node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"